client_configs:
  train_configs:
    trainer: NaiveTrainer
    mode: step
    num_local_steps: 10
    optim: SGD
    optim_args:
      lr: 0.01
    seed: 42
    loss_fn_path: ./loss/celoss.py
    loss_fn_name: CELoss
    do_validation: false
    do_pre_validation: false
    metric_path: ./metric/acc.py
    metric_name: accuracy
    use_dp: false
    epsilon: 1
    clip_grad: false
    clip_value: 1
    clip_norm: 1
    send_gradient: true
    train_batch_size: 128
    val_batch_size: 128
    train_data_shuffle: true
    val_data_shuffle: false
  model_configs:
    model_path: ./model/cifar_resnet.py
    model_name: ResNet18
    model_kwargs:
      in_channels: 3
      num_classes: 10
      base_channels: 64
      stem_kernel_size: 3
      stem_stride: 1
      stem_padding: 1
      use_maxpool: false
      avgpool_kernel_size: 4
      avgpool_stride: 4
  comm_configs:
    compressor_configs:
      enable_compression: false
      lossy_compressor: SZ2
      lossless_compressor: blosc
      error_bounding_mode: REL
      error_bound: 0.001
      flat_model_dtype: np.float32
      param_cutoff: 1024
server_configs:
  scheduler: CompassScheduler
  scheduler_kwargs:
    num_clients: 10
    same_init_model: true
    max_local_steps: 10
    min_local_steps: 2
    speed_momentum: 0.9
    latest_time_factor: 1.2
  aggregator: FedCompassAggregator
  aggregator_kwargs:
    weights: equal
    staleness_fn: polynomial
    staleness_fn_kwargs:
      a: 0.5
    alpha: 0.9
    gradient_based: true
    num_clients: 10
  seed: 42
  device: cpu
  num_global_epochs: 20000
  server_validation: true
  validation_data_configs:
    dataset_path: ./dataset/cifar10_dataset.py
    dataset_name: get_cifar10
    dataset_kwargs:
      num_clients: 10
      client_id: 0
      partition_strategy: class_noniid
      min_classes_per_client: 3
      max_classes_per_client: 5
      class_partition_alpha: 1.0
      seed: 233
      normalize_mean:
      - 0.4914
      - 0.4822
      - 0.4465
      normalize_std:
      - 0.247
      - 0.2435
      - 0.2616
  logging_output_dirname: ./output
  logging_output_filename: result
  comm_configs:
    grpc_configs:
      server_uri: localhost:50051
      max_message_size: 1048576
      use_ssl: false
      max_workers: 32
